### ISSUE TITLE
ユーザーは、デザインを適用したトップページを確認出来る

### ISSUE THREAD

**Issue by kokuyouwind** [aria-company/how-is-the-progress#15]
雑デザインになってるので何とかする

**Comment by nanocitrus** [comment]
![howistheprogress1](https://cloud.githubusercontent.com/assets/6778507/8392272/346b53fc-1d20-11e5-87ea-066bb0a65444.jpg)
![howistheprogress2](https://cloud.githubusercontent.com/assets/6778507/8392273/34703dd6-1d20-11e5-989b-b2df4b7dde06.jpg)
